import React from 'react'
import './Form.css'
import user from '../../Images/user.svg'
import done from '../../Images/done.svg'
import FormStep1 from './FormStep1'
import FormStep2 from './FormStep2'
import FormStep3 from './FormStep3'
import { Link } from 'react-router-dom'

function Form({ setShowForm }) {

    const color = `green`

    const [currentStep, setStep] = React.useState(1)

    const [data, setData] = React.useState([
        {
            name: '',
            email: '',
            phone: '',
            age: '',
            city: '',
            instagram: '',
            instaFollowers: '',
            onlyFans: '',
            onlyFansFollowers: '',
            education: '',
            degree: '',
            languages: '',
            answer: ''
        }
    ])

    const [finishSteps, setFinishSteps] = React.useState(0)

    return (
        <div className='formBlock'>
            <div className='formClose'>
                <button onClick={() => setShowForm(false)}>
                <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 384 512"><path d="M376.6 84.5c11.3-13.6 9.5-33.8-4.1-45.1s-33.8-9.5-45.1 4.1L192 206 56.6 43.5C45.3 29.9 25.1 28.1 11.5 39.4S-3.9 70.9 7.4 84.5L150.3 256 7.4 427.5c-11.3 13.6-9.5 33.8 4.1 45.1s33.8 9.5 45.1-4.1L192 306 327.4 468.5c11.3 13.6 31.5 15.4 45.1 4.1s15.4-31.5 4.1-45.1L233.7 256 376.6 84.5z"/></svg>
                    </button>   
            </div>
            <iframe className='iframeForm' src="https://morgis.formstack.com/forms/morgi_form" title="Morgi Form" width="100%" height="400"></iframe>

            <div className="formBottom">
                <p>Never submit passwords or sensitive data through unknown forms. Make sure this form was generated by your company or a trusted company.</p>
                <div className='footerLinks'>
                    <Link to='#'>Report abuse</Link>
                    <p>|</p>
                    <Link to='#'>Terms and Conditions</Link>
                </div>
            </div>

            {
                /* 
                <div className="stepBar">
                                <div className="stepLine">
                                    <div className="stepLineWrapper">
                                        <div className="stepLineLine" style={{ width: currentStep === 1 ? 0 + '%' : currentStep === 2 ? 50 + '%' : 100 + '%' }}></div>
                                    </div>
                                    <div className={`stepCircle ${currentStep >= 1 && 'stepActive'}`}>
                                        <img src={currentStep > 1 ? done : user} alt="User" />
                                    </div>
                                    <div className={`stepCircle ${currentStep >= 2 && 'stepActive'}`}>
                                        <img src={currentStep > 2 ? done : user} alt="User" />
                                    </div>
                                    <div className={`stepCircle ${currentStep >= 3 && 'stepActive'}`}>
                                        <img src={currentStep > 3 ? done : user} alt="User" />
                                    </div>
                                </div>
                            </div>
                
                            <div className="formContent">
                                {currentStep === 1 && (
                                    <FormStep1 color={'green'} setData={setData} data={data} setStep={setStep} finishSteps={finishSteps} setFinishSteps={setFinishSteps} />
                                )}
                                {currentStep === 2 && (
                                    <FormStep2 color={'green'} setData={setData} data={data} setStep={setStep} finishSteps={finishSteps} setFinishSteps={setFinishSteps} />
                                )}
                                {currentStep === 3 && (
                                    <FormStep3 color={'green'} setData={setData} data={data} setStep={setStep} finishSteps={finishSteps} setFinishSteps={setFinishSteps} setShowForm={setShowForm} />
                                )}
                            </div>
                
                */
            }
        </div>
    )
}

export default Form